### ISSUE TITLE
Windows support

### ISSUE THREAD

**Issue by zumoshi** [leonsmith/pydig#14]
Hi
On windows, dig's output may be separated by CRLF instead of LF.
![image](https://user-images.githubusercontent.com/4184939/102679848-16fee400-41c8-11eb-97c2-957a8f5a0b84.png)
Would you like me to create a pull request to handle both CRLF and LF correctly or is windows not supported?

Thanks

**Comment by leonsmith** [comment]
Good spot! Windows isn't officially supported but we could add adjustable line endings to help this along.
I can get it added & tested soon 👍

**Comment by leonsmith** [comment]
Sorry I haven't got time to tweak this (or a meaningfull way to test on a real windows machine)
