### ISSUE TITLE
Specify Port Number

### ISSUE THREAD

**Issue by pizu** [leonsmith/pydig#18]
Hi,

Is it possible to specify the port number in the resolver? if not is it possible to have this feature? 

Thanks.

**Comment by leonsmith** [comment]
you should be able to use the additional args on a custom resolver

```bash
resolver = pydig.Resolver(
    nameservers=[
        '1.1.1.1',
        '1.0.0.1',
    ],
    additional_args=[
        '-p 5333',
    ]
)
resolver.query('example.com', 'A')
```

**Comment by leonsmith** [comment]
Hopefully that helps!
